# Generated by Django 2.0.1 on 2018-01-13 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('fee', models.IntegerField(default=100)),
                ('maxTeamSize', models.IntegerField(default=1)),
                ('teamEvent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=200)),
                ('phonenumber', models.IntegerField()),
                ('dob', models.DateField()),
                ('eventsPaid', models.CharField(max_length=400)),
                ('eventsPending', models.CharField(max_length=400)),
                ('totalPaid', models.IntegerField()),
                ('unpaidAmount', models.IntegerField()),
                ('teamNames', models.CharField(max_length=600)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
