# Generated by Django 2.0.1 on 2018-01-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebooklogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='maxTeamSize',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='eventsPaid',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='eventsPending',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='teamNames',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='totalPaid',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='unpaidAmount',
            field=models.IntegerField(blank=True),
        ),
    ]
