# Generated by Django 2.0.1 on 2018-01-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebooklogin', '0002_auto_20180114_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='totalPaid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='unpaidAmount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
