# Generated by Django 2.0.1 on 2018-01-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebooklogin', '0004_auto_20180114_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='teamNames',
            field=models.TextField(blank=True),
        ),
    ]
