# Generated by Django 2.0.1 on 2018-02-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebooklogin', '0006_paymentinitiated'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsMade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=500)),
                ('user_email', models.CharField(max_length=500)),
                ('payment_request_id', models.CharField(max_length=500)),
                ('payment_id', models.CharField(max_length=500)),
            ],
        ),
    ]
