# Generated by Django 2.0.1 on 2018-02-03 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebooklogin', '0007_paymentsmade'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.CharField(blank=True, max_length=1000)),
                ('amount', models.IntegerField(blank=True)),
                ('payment_id', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='facebooklogin.UserProfile')),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentsMade',
        ),
    ]
