# Generated by Django 2.0.1 on 2018-02-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebooklogin', '0008_auto_20180203_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aadharNumber',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
