# Generated by Django 2.0.1 on 2018-02-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebooklogin', '0009_userprofile_aadharnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='aadharNumber',
            field=models.CharField(blank=True, default='AadharNumber', max_length=12),
        ),
    ]
