# Generated by Django 2.0.1 on 2018-02-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebooklogin', '0010_auto_20180210_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='aadharNumber',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
