# Generated by Django 2.0.1 on 2018-02-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebooklogin', '0011_auto_20180210_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roll_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
